#!/bin/sh

# Prepare ------------------------------------------------------------------------------------------
# Check if user flags for specific pokemon
pokemon="$((1 + RANDOM % 905))"


data_pokemon=$(curl -fsLS "https://pokeapi.co/api/v2/pokemon/${pokemon}")
data_species=$(curl -fsLS "$(echo "${data_pokemon}" | jq --raw-output .species.url)")

clean_species=$(echo "$data_species" | tr -d '\000-\031')

id=$(echo "${clean_species}" | jq --raw-output .id)
name=$(echo "${clean_species}" | jq --raw-output '.names | .[] | select(.language.name == "en").name')
category=$(echo "${clean_species}" | jq --raw-output '.genera | .[] | select(.language.name == "en").genus')
title="▐[1;7m No.$(printf '%03d' "${id}") [0m▌ [1m${name} - ${category}[0m"

 
for type in $(echo "${data_pokemon}" | jq --raw-output '.types | .[].type.name' | tr '[:lower:]' '[:upper:]'); do
	case "${type}" in
		NORMAL)   color=7  ;;
		FIRE)     color=9  ;;
		WATER)    color=12 ;;
		ELECTRIC) color=11 ;;
		GRASS)    color=10 ;;
		ICE)      color=14 ;;
		FIGHTING) color=1  ;;
		POISON)   color=5  ;;
		GROUND)   color=11 ;;
		FLYING)   color=6  ;;
		PSYCHIC)  color=13 ;;
		BUG)      color=2  ;;
		ROCK)     color=3  ;;
		GHOST)    color=4  ;;
		DRAGON)   color=4  ;;
		DARK)     color=3  ;;
		STEEL)    color=8  ;;
		FAIRY)    color=13 ;;
	esac

	types="${types} [7;38;5;${color}m ${type} [0m "
done

height=$(awk "BEGIN{ print $(echo "${data_pokemon}" | jq --raw-output .height) / 10 }")
weight=$(awk "BEGIN{ print $(echo "${data_pokemon}" | jq --raw-output .weight) / 10 }")
status=$(gum style --align center --width 44 "${types}" "Height: [1m${height}m[0m      Weight: [1m${weight}kg[0m")

info=$(gum join --vertical "${title}" '' "${status}")

entries=$(gum style --border normal --padding '0 1' --width 42 "$(echo "${clean_species}" | \
jq --raw-output 'last(.flavor_text_entries | .[] | select(.language.name == "en")).flavor_text' | tr -d "\n")")

pokemon_path=$(echo "${data_pokemon}" | jq --raw-output .name)
art_raw=$(curl -fsLS \
"https://gitlab.com/phoneybadger/pokemon-colorscripts/-/raw/main/colorscripts/small/regular/${pokemon_path}" \
| sed -e 's/$/[0m/g')

if [ -z "$art_raw" ]; then
  art="(no art)"
else
  art=$(gum style "$(echo "$art_raw")")
fi

# Display ------------------------------------------------------------------------------------------

terminal_size=$(stty size)
terminal_height=${terminal_size% *}
terminal_width=${terminal_size#* }

prompt_height=${PROMPT_HEIGHT:-1}


print_test() {
	gum style --align center --width="${terminal_width}" "${1}" ''
	exit 0
}


# Landscape layout
group_info_entries=$(gum join --vertical "${info}" '' "${entries}")
print_test "$(gum join --horizontal --align center "${art}" '  ' "${group_info_entries}")"

# Portrait layout
print_test "$(gum join --vertical --align center "${info}" '' "${art}" "${entries}")"

# Other layout
print_test "${group_info_entries}"

exit 1
